name: C/C++ CI

on:
  push:
    branches: [ "addCiCd" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
          release: '9-2019-q4'
      
    - name: Build Firmware
      run: make -j4
      
    - name: Upload ELF
      uses: actions/upload-artifact@v2
