name: C/C++ CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
       release: '10-2020-q4' # The arm-none-eabi-gcc release to use
    
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
       platform: x64
       packages: cmake gcc-g++
       
    - name: Build & Test
      uses: ashutoshvarma/action-cmake-build@master
      with:
          build-dir: ${{ runner.workspace }}/build
          # will set the CC & CXX for cmake
          cc: gcc
          cxx: g++
          build-type: Debug
          # Extra options pass to cmake while configuring project
          configure-options: -DCMAKE_C_FLAGS=-w32 -DPNG_INCLUDE=OFF
          #run-test: true
          #ctest-options: -R mytest
          # install the build using cmake --install
          #install-build: true
          # run build using '-j [parallel]' to use multiple threads to build
         # parallel: 14
