name: C/C++ CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
 job_linux_20_04_64_gcc:
    name: ubuntu-20.04 gcc
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt-get install gcc-10 libusb-1.0.0-dev libgtk-3-dev rpm && sudo apt install cmake
      - name: cmake go to directory
        run: cd /home/runner/work/Pult/Pult/
      - name: cmake build
        run: sudo cmake --build
      - name: make test
        run: sudo make clean && make test
      - name: make release
        run: sudo make clean && make release
      - name: sudo make install
        run: sudo make clean && sudo make install
      - name: sudo make package
        run: sudo make package
      - name: sudo make uninstall
        run: sudo make uninstall && sudo make clean
