name: C/C++ CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
 job_linux_20_04_64_gcc:
    name: ubuntu-20.04 gcc
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: arm-none-eabi-gcc
        uses: fiam/arm-none-eabi-gcc@v1.0.2
        with:
          release: 10-2020-q4
          
      - name: Build CMake
      # You may pin to the exact commit or the version.
      # uses: ashutoshvarma/action-cmake-build@0fbeeac8b1f9c8aef99e9eae9d78529ed3b0364b
        uses: ashutoshvarma/action-cmake-build@v1
        with:
          # Build directory where build files will be generated
          build-dir: ${{ runner.workspace }}/build
          # CMake build type (Release, Debug, MinSizeRel, RelWithDebInfo)
          build-type: Debug
          # C Compiler for toolchain
          cc: arm-none-eabi-gcc
          # C++ Compiler for toolchain
          cxx: arm-none-eabi-g++
          # CMake build target
          target: Pult.elf
          # Number of concurrent jobs for build and test

          
